// <auto-generated/>

using System;
using Newtonsoft.Json.Linq;
using navidataIO.Utils.IO;
                    
namespace FabricTools.Items.Report.Definitions;

#nullable enable

public partial class Report : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "report.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class Page : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "page.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class VisualContainer : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "visual.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class Bookmark : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; }
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class BookmarksMetadata : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "bookmarks.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class PagesMetadata : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "pages.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class ReportExtension : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "reportExtensions.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class VersionMetadata : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "version.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

public partial class VisualContainerMobileState : IPbirDocument
{
    #region IPbirDocument
                        
    RelativeFilePath? IPbirDocumentNode.Path { get; set; } = "mobile.json";
                       
    IPbirDocumentNode? IPbirDocumentNode.Parent { get; set; }
                        
    JObject? IPbirDocument.OriginalJson { get; set; }
                                            
    #endregion
}

