// <auto-generated/>

using System;

namespace FabricTools.Items.Report.Definitions;

#nullable enable

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
sealed class PbirDocumentAttribute : Attribute
{
    public string? DefaultPath { get; }
    public PbirDocumentAttribute(string? defaultPath = null)
    {
        DefaultPath = defaultPath;
    }
}