//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:BookmarkOptions")]
public partial class BookmarkOptions
{
    /// <summary>
    /// Only applies changes to selected visuals when the bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("applyOnlyToTargetVisuals", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool ApplyOnlyToTargetVisuals { get; set; } = default!;

    /// <summary>
    /// Specific visuals to which this bookmark applies.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("targetVisualNames", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string> TargetVisualNames { get; set; } = default!;

    /// <summary>
    /// Don't apply changes to active section.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("suppressActiveSection", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool SuppressActiveSection { get; set; } = default!;

    /// <summary>
    /// Don't apply data changes.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("suppressData", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool SuppressData { get; set; } = default!;

    /// <summary>
    /// Don't apply display property changes.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("suppressDisplay", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool SuppressDisplay { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:ExplorationState")]
public partial class BookmarkExplorationState
{
    /// <summary>
    /// Version of bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Version { get; set; } = default!;

    /// <summary>
    /// Name of the page that was active when this bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("activeSection", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string ActiveSection { get; set; } = default!;

    /// <summary>
    /// State of filters for the report when the bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkFiltersState Filters { get; set; } = default!;

    /// <summary>
    /// State of all pages when the bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("sections", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.IDictionary<string, BookmarkSectionState> Sections { get; set; } = new System.Collections.Generic.Dictionary<string, BookmarkSectionState>();

    /// <summary>
    /// Changes to formatting to apply in this bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("objects", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkDataViewObjectDefinitionUpdates Objects { get; set; } = default!;

    /// <summary>
    /// A string containing the state of any variables from the underlying direct query data source that should be overridden when rendering this content.
    /// <br/>Data source variables do not supply values for M parameters in the semantic model. Instead, data source variables are applied when accessing the underlying direct query source.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataSourceVariables", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string DataSourceVariables { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:FiltersState")]
public partial class BookmarkFiltersState
{
    /// <summary>
    /// Filter containers that will be identified by name.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("byName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, BookmarkFilterContainerState> ByName { get; set; } = default!;

    /// <summary>
    /// Filter containers that will be identified by expression.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("byExpr", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<BookmarkFilterContainerState> ByExpr { get; set; } = default!;

    /// <summary>
    /// Filter containers that will be identified by type.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("byType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<BookmarkFilterContainerState> ByType { get; set; } = default!;

    /// <summary>
    /// Filter containers that are transient
    /// </summary>
    [Newtonsoft.Json.JsonProperty("byTransientState", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<BookmarkFilterContainerState> ByTransientState { get; set; } = default!;


}

/// <summary>
/// Meaning of properties is same as Filters defined outside the bookmark.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:FilterContainerState")]
public partial class BookmarkFilterContainerState
{
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Type { get; set; } = default!;

    /// <summary>
    /// Defines a filter element as a partial query structure
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filter", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public FilterDefinition Filter { get; set; } = default!;

    /// <summary>
    /// Holds a single expression and associated metadata.
    /// <br/>Name, NativeReferenceName, and Annotations may be specified for any expression.
    /// <br/>Each other property represents a specific type of expression and exactly one of these other properties must be specified.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("expression", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public QueryExpressionContainer Expression { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("restatement", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Restatement { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("howCreated", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkFilterContainerStateHowCreated HowCreated { get; set; } = default!;

    /// <summary>
    /// Precedence of the filter.  The higher the number, the higher the precedence of the filter.
    /// <br/>
    /// <br/>Each filter is evaluated in the presence of other filters which are strictly higher precedence,
    /// <br/>and in the absense of all filters which are equal or lower precedence.
    /// <br/>
    /// <br/>Note that not all precedence levels are encoded here yet.  For example, cross filters have higher
    /// <br/>precedence than data filters, and data filters have higher precedence than drill filters.  Neither
    /// <br/>cross filters nor data filters have an entry in this enumeration yet, but instead have their
    /// <br/>precedence enforced by explicit code in the FilterGenerator.  It is a future work item to encode
    /// <br/>all precendence levels here.
    /// <br/>
    /// <br/>Note also that when we add new precedence levels in this enumeration, we may have to change existing
    /// <br/>precedence levels.  If that happens, we will need to add Upgrader code to translate the precedence
    /// <br/>levels from one version to another.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("precedence", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Precedence { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("isTransient", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool IsTransient { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("cachedDisplayNames", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<Newtonsoft.Json.Linq.JToken> CachedDisplayNames { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("filterExpressionMetadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken FilterExpressionMetadata { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:SectionState")]
public partial class BookmarkSectionState
{
    /// <summary>
    /// State of filters for this page when the bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkFiltersState Filters { get; set; } = default!;

    /// <summary>
    /// Flat list of visual-container-specific state.
    /// <br/>Does not include state of groups.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualContainers", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.IDictionary<string, BookmarkVisualContainerState> VisualContainers { get; set; } = new System.Collections.Generic.Dictionary<string, BookmarkVisualContainerState>();

    /// <summary>
    /// Flat list of group-specific state.
    /// <br/>Does not include state of visual containers.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualContainerGroups", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, BookmarkVisualContainerGroupState> VisualContainerGroups { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerState")]
public partial class BookmarkVisualContainerState
{
    /// <summary>
    /// State of filters for this page when the bookmark was captured.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkFiltersState Filters { get; set; } = default!;

    /// <summary>
    /// State of the configuration of the visual.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("singleVisual", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkSingleVisualConfigState SingleVisual { get; set; } = default!;

    /// <summary>
    /// Cross-highlights captured in the bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("highlight", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkHighlightState Highlight { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:SingleVisualConfigState")]
public partial class BookmarkSingleVisualConfigState
{
    /// <summary>
    /// Name of visual
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string VisualType { get; set; } = default!;

    /// <summary>
    /// Can the visual type change as data changes in the bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("autoSelectVisualType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool AutoSelectVisualType { get; set; } = default!;

    /// <summary>
    /// Change visual to this type - if different from the original state. Used by personalize this visual on the web.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("targetType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string TargetType { get; set; } = default!;

    /// <summary>
    /// Change auto changing visual type.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("targetAutoSelectVisualType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool TargetAutoSelectVisualType { get; set; } = default!;

    /// <summary>
    /// Changes to formatting to apply in this bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("objects", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkDataViewObjectDefinitionUpdates Objects { get; set; } = default!;

    /// <summary>
    /// Updated ordering of data.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("orderBy", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<QuerySortClause> OrderBy { get; set; } = default!;

    /// <summary>
    /// Updated projections that are used by the visual.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("activeProjections", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkProjectionState ActiveProjections { get; set; } = default!;

    /// <summary>
    /// Projections are stored only when presentation changes are applied (such as during personalize visuals)
    /// <br/>or if the projections are resolved projections of a field parameter. When projections are resolved
    /// <br/>projections of a field parameter but presentation changes are not applied, nulls will be present in the
    /// <br/>array to indicate where non-parameter projections of the visual are.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("projections", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkProjectionState Projections { get; set; } = default!;

    /// <summary>
    /// Field parameters that were used as part of the query. We always capture parameter state when parameters
    /// <br/>are present regardless of the bookmark type.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("parameters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkParameterStateByRole Parameters { get; set; } = default!;

    /// <summary>
    /// Optional changes to how the visual is displayed.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("display", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkVisualContainerDisplayState Display { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("cachedFilterDisplayItems", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<Newtonsoft.Json.Linq.JToken> CachedFilterDisplayItems { get; set; } = default!;

    /// <summary>
    /// Changes to expansion state.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("expansionStates", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<Newtonsoft.Json.Linq.JToken> ExpansionStates { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("filterExpressionMetadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken FilterExpressionMetadata { get; set; } = default!;

    /// <summary>
    /// Indicates whether the drill feature is disabled
    /// </summary>
    [Newtonsoft.Json.JsonProperty("isDrillDisabled", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool IsDrillDisabled { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:DataViewObjectDefinitionUpdates")]
public partial class BookmarkDataViewObjectDefinitionUpdates
{
    /// <summary>
    /// ObjectDefinitions to be merged with the target.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("merge", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<DataViewObjectDefinition>> Merge { get; set; } = default!;

    /// <summary>
    /// ObjectDefinitions to be deleted from the existing instances.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("remove", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<BookmarkDataViewObjectPropertyIdWithSelector> Remove { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:DataViewObjectPropertyIdWithSelector")]
public partial class BookmarkDataViewObjectPropertyIdWithSelector
{
    /// <summary>
    /// Name of visual object.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("object", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Object { get; set; } = default!;

    /// <summary>
    /// Name of property to change for the visual object.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("property", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Property { get; set; } = default!;

    /// <summary>
    /// Scope at which to apply this change.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public Selector Selector { get; set; } = new Selector();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:ProjectionState")]
public partial class BookmarkProjectionState : System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<QueryExpressionContainer>>
{

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:ParameterStateByRole")]
public partial class BookmarkParameterStateByRole : System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<BookmarkParameterState>>
{

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:ParameterState")]
public partial class BookmarkParameterState
{
    /// <summary>
    /// Parameter expression.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("expr", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public QueryExpressionContainer Expr { get; set; } = new QueryExpressionContainer();

    /// <summary>
    /// Index from which parameter starts in the visual projection.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("index", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Index { get; set; } = default!;

    /// <summary>
    /// Number of fields created by the parameter.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("length", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Length { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerDisplayState")]
public partial class BookmarkVisualContainerDisplayState
{
    /// <summary>
    /// How is this visual shown in the bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("mode", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public BookmarkVisualContainerDisplayMode Mode { get; set; } = default!;

    /// <summary>
    /// Options if maximized.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("maximizedOptions", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkVisualContainerDisplayStateMaximizedOptions MaximizedOptions { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerDisplayMode")]
public enum BookmarkVisualContainerDisplayMode
{

    [System.Runtime.Serialization.EnumMember(Value = @"maximize")]
    /// <summary>Visual is shown full screen.</summary>
    Maximize,

    [System.Runtime.Serialization.EnumMember(Value = @"spotlight")]
    /// <summary>Visual is spotlighted and other visuals on the page are dimmed.</summary>
    Spotlight,

    [System.Runtime.Serialization.EnumMember(Value = @"elevation")]
    /// <summary>Visual is shown with an elevation.</summary>
    Elevation,

    [System.Runtime.Serialization.EnumMember(Value = @"hidden")]
    /// <summary>Visual is hidden.</summary>
    Hidden,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:HighlightState")]
public partial class BookmarkHighlightState
{
    /// <summary>
    /// Data points selected for the highlights.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selection", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public AnyOfTypes.AnyOf<BookmarkDecomposedSelectors, System.Collections.Generic.ICollection<BookmarkSelectorsByColumn>>? Selection { get; set; } = default!;

    /// <summary>
    /// Additional metadata for the filter generated from highlights.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filterExpressionMetadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken FilterExpressionMetadata { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:DecomposedSelectors")]
public partial class BookmarkDecomposedSelectors
{
    [Newtonsoft.Json.JsonProperty("decomposedIdentities", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkDecomposedIdentities DecomposedIdentities { get; set; } = default!;

    /// <summary>
    /// The `queryNameIndex` key is the index in the queryNames array;
    /// <br/>the `number` value is the columnIndex properties in DecomposedScopeIdentity.
    /// <br/>This map tracks the different queryName and their column shapes present in each dataMap
    /// </summary>
    [Newtonsoft.Json.JsonProperty("queryNameMap", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<double>>> QueryNameMap { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("queryNames", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string> QueryNames { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<System.Collections.Generic.ICollection<string>> Metadata { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string> Id { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:DecomposedIdentities")]
public partial class BookmarkDecomposedIdentities
{
    /// <summary>
    /// `values` have 3 levels
    /// <br/>outermost level:
    /// <br/> - for SelectorsByColumn[], it's the number of selectors in this array
    /// <br/> - for FilterExpressionMetadata, it's the number of cachedValueItems.
    /// <br/>second level:
    /// <br/>  - for SelectorsByColumn, it is the number of scopedIdentities in the particular SelectorsByColumn
    /// <br/>  - for FilterExpressionMetadata, it is the number of identities in a cachedValueItem
    /// <br/>innermost level:
    /// <br/>  - the key is the index of the column structure of scopedIdentity in `columns` list;
    /// <br/>  - the the value is the expressions list in one identity
    /// </summary>
    [Newtonsoft.Json.JsonProperty("values", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<System.Collections.Generic.ICollection<System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<QueryExpressionContainer>>>> Values { get; set; } = new System.Collections.ObjectModel.Collection<System.Collections.Generic.ICollection<System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<QueryExpressionContainer>>>>();

    /// <summary>
    /// Defines the set of group-on key columns.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("columns", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<BookmarkDecomposedTree<QueryExpressionContainer>> Columns { get; set; } = new System.Collections.ObjectModel.Collection<BookmarkDecomposedTree<QueryExpressionContainer>>();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:DecomposedTree<QueryExpressionContainer>")]
public partial class BookmarkDecomposedTree<QueryExpressionContainer>
{
    [Newtonsoft.Json.JsonProperty("left", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkDecomposedTree<QueryExpressionContainer> Left { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("right", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkDecomposedTree<QueryExpressionContainer> Right { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public QueryExpressionContainer Value { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:SelectorsByColumn")]
public partial class BookmarkSelectorsByColumn
{
    [Newtonsoft.Json.JsonProperty("dataMap", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkSelectorsForColumn DataMap { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string> Metadata { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Id { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:SelectorsForColumn")]
public partial class BookmarkSelectorsForColumn : System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<DataRepetitionSelector>>
{

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerGroupState")]
public partial class BookmarkVisualContainerGroupState
{
    /// <summary>
    /// Is the group hidden in the bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("isHidden", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool IsHidden { get; set; } = default!;

    /// <summary>
    /// State of child groups.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("children", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, BookmarkVisualContainerGroupState> Children { get; set; } = default!;


}

/// <summary>
/// Defines a bookmark that captures the state of a report.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json")]
public partial class Bookmark
{
    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json";

    /// <summary>
    /// Display name for the bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("displayName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string DisplayName { get; set; } = default!;

    /// <summary>
    /// Unique identifier for the bookmark - unique across the report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Additional options for the bookmark
    /// </summary>
    [Newtonsoft.Json.JsonProperty("options", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public BookmarkOptions Options { get; set; } = default!;

    /// <summary>
    /// Bookmark definition to use when applying this bookmark.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("explorationState", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public BookmarkExplorationState ExplorationState { get; set; } = new BookmarkExplorationState();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:FilterContainerState/howCreated")]
public enum BookmarkFilterContainerStateHowCreated
{

    /// <summary>0</summary>
    _0 = 0,

    /// <summary>1</summary>
    _1 = 1,

    /// <summary>2</summary>
    _2 = 2,

    /// <summary>3</summary>
    _3 = 3,

    /// <summary>4</summary>
    _4 = 4,

    /// <summary>5</summary>
    _5 = 5,

    /// <summary>6</summary>
    _6 = 6,

    /// <summary>7</summary>
    _7 = 7,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerDisplayState/maximizedOptions")]
public partial class BookmarkVisualContainerDisplayStateMaximizedOptions
{
    /// <summary>
    /// Type of table to show.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataTable", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public BookmarkVisualContainerDisplayStateMaximizedOptionsDataTable DataTable { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmark/1.2.0/schema.json", "definitions:VisualContainerDisplayState/maximizedOptions/dataTable")]
public enum BookmarkVisualContainerDisplayStateMaximizedOptionsDataTable
{

    [System.Runtime.Serialization.EnumMember(Value = @"accessible")]
    Accessible = 0,

    [System.Runtime.Serialization.EnumMember(Value = @"normal")]
    Normal = 1,

}