//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

/// <summary>
/// Defines a bookmark that is not part of a group (standalone bookmark).
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmarksMetadata/1.0.0/schema.json", "definitions:SingleBookmarkMetadata")]
public partial class BookmarksMetadataSingleBookmarkMetadata
{
    /// <summary>
    /// Name of the bookmark - use if not under a specific group. Should be unique across the report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;


}

/// <summary>
/// Defines a group of related bookmarks.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmarksMetadata/1.0.0/schema.json", "definitions:BookmarkGroupMetadata")]
public partial class BookmarksMetadataBookmarkGroupMetadata
{
    /// <summary>
    /// Name of the bookmark group - unique across the report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Display name of the group.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("displayName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string DisplayName { get; set; } = default!;

    /// <summary>
    /// Name of the bookmarks under this group.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("children", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<string> Children { get; set; } = new System.Collections.ObjectModel.Collection<string>();


}

/// <summary>
/// Defines additional information about standalone bookmarks or groups of related bookmarks.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmarksMetadata/1.0.0/schema.json")]
public partial class BookmarksMetadata
{
    [Newtonsoft.Json.JsonProperty("items", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<AnyOfTypes.AnyOf<BookmarksMetadataSingleBookmarkMetadata, BookmarksMetadataBookmarkGroupMetadata>> Items { get; set; } = new System.Collections.ObjectModel.Collection<AnyOfTypes.AnyOf<BookmarksMetadataSingleBookmarkMetadata, BookmarksMetadataBookmarkGroupMetadata>>();

    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/bookmarksMetadata/1.0.0/schema.json";


}