//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataViewObjectDefinitions")]
public partial class DataViewObjectDefinitions : System.Collections.Generic.Dictionary<string, System.Collections.ObjectModel.Collection<DataViewObjectDefinition>>
{

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataViewObjectDefinition")]
public partial class DataViewObjectDefinition
{
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector Selector { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public DataViewObjectPropertyDefinitions Properties { get; set; } = new DataViewObjectPropertyDefinitions();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataViewObjectPropertyDefinitions")]
public partial class DataViewObjectPropertyDefinitions : System.Collections.Generic.Dictionary<string, Newtonsoft.Json.Linq.JToken>
{

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:Selector")]
public partial class Selector
{
    /// <summary>
    /// Scope is defined by data bound to the visual.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("data", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<DataRepetitionSelector> Data { get; set; } = default!;

    /// <summary>
    /// Defines the scope to a specific field.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("metadata", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Metadata { get; set; } = default!;

    /// <summary>
    /// User defined scope.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Id { get; set; } = default!;

    /// <summary>
    /// Describes how the Selector should behave towards Highlighted Values within the Scope matched by that Selector.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("highlightMatching", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public SelectorHighlightMatching HighlightMatching { get; set; } = default!;

    /// <summary>
    /// Specifies a user-defined ordering of identical properties.
    /// <br/>Selector constructors should strive to monitonically increase this number across identical properties differing by id.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("order", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Order { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataRepetitionSelector")]
public partial class DataRepetitionSelector
{
    /// <summary>
    /// Defines the intersection of scopes. For example - product color = red.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("scopeId", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public QueryExpressionContainer ScopeId { get; set; } = default!;

    /// <summary>
    /// Defines a match against all instances of a given DataView scope. Does not match Subtotals.
    /// <br/>Deprecated: - Use roles instead.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("wildcard", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<QueryExpressionContainer> Wildcard { get; set; } = default!;

    /// <summary>
    /// Matches against all fields in a role.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("roles", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string> Roles { get; set; } = default!;

    /// <summary>
    /// Matches against the totals and subtotals.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("total", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<QueryExpressionContainer> Total { get; set; } = default!;

    /// <summary>
    /// Matches all instances or all totals or both.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataViewWildcard", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public DataViewWildcard DataViewWildcard { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataViewWildcard")]
public partial class DataViewWildcard
{
    /// <summary>
    /// Defines the matching option to use.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("matchingOption", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public DataViewWildcardMatchingOption MatchingOption { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:DataViewWildcardMatchingOption")]
public enum DataViewWildcardMatchingOption
{

    /// <summary>Match Identities and Totals (default)</summary>
    _0 = 0,

    /// <summary>Match Instances with Identities only</summary>
    _1 = 1,

    /// <summary>Match Totals only</summary>
    _2 = 2,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-48+Branch.main.Sha.e5ee63afa02697f49e23bed6be2f4d612638ddc4.e5ee63afa02697f49e23bed6be2f4d612638ddc4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/formattingObjectDefinitions/1.2.0/schema.json", "definitions:Selector/highlightMatching")]
public enum SelectorHighlightMatching
{

    /// <summary>Only non-highlighted value will be selected, even if a highlighted value exists.</summary>
    _0 = 0,

    /// <summary>Non-highlighted values are selected. If highlighted values exist, they are selected as well.</summary>
    _1 = 1,

    /// <summary>If a highlighted value exists, it's selected. Otherwise, the non-highlighted value is selected.</summary>
    _2 = 2,

}