//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

/// <summary>
/// Defines additional information about the report's pages.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/pagesMetadata/1.0.0/schema.json")]
public partial class PagesMetadata
{
    /// <summary>
    /// Defines the order in which report pages are rendered (page names). If omitted, they will be ordered by display name by default.
    /// <br/>If there are pages in this list, that don't have a corresponding definition, they will be ignored.
    /// <br/>Pages with definitions, but not in this list will be ordered by display name and appended to the end, after pages that exist in this list.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("pageOrder", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<string>? PageOrder { get; set; } = default!;

    /// <summary>
    /// Report will open on this page by default - if omitted, report will open on first page based on order defined by pageOrder semantics.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("activePageName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string? ActivePageName { get; set; } = default!;

    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/pagesMetadata/1.0.0/schema.json";


}