//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageDisplayOption")]
public enum PageDisplayOption
{

    [System.Runtime.Serialization.EnumMember(Value = @"DeprecatedDynamic")]
    /// <summary>No dynamic page without width or height.
    /// <br/>Deprecated: Use other display options.</summary>
    DeprecatedDynamic,

    [System.Runtime.Serialization.EnumMember(Value = @"FitToPage")]
    /// <summary>Page is scaled so both width and height fit on the current viewport.</summary>
    FitToPage,

    [System.Runtime.Serialization.EnumMember(Value = @"FitToWidth")]
    /// <summary>Only width is scaled to fit on the current viewport, height will be updated to maintain page aspect ratio.</summary>
    FitToWidth,

    [System.Runtime.Serialization.EnumMember(Value = @"ActualSize")]
    /// <summary>No scaling is done - page is centered relative to the report canvas.</summary>
    ActualSize,

    [System.Runtime.Serialization.EnumMember(Value = @"ActualSizeTopLeft")]
    /// <summary>No scaling is done - page is anchored to top-left corder relative to the report canvas.
    /// <br/>Deprecated: Use ActualSize instead.</summary>
    ActualSizeTopLeft,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageBinding")]
public partial class PageBinding
{
    /// <summary>
    /// Name of this binding - unique across the report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Specific usage of this binding (for example drillthrough).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public PageBindingType Type { get; set; } = default!;

    /// <summary>
    /// What is the scope under which the binding applies.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("referenceScope", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageBindingReferenceScope? ReferenceScope { get; set; } = PageBindingReferenceScope.Default;

    /// <summary>
    /// Additional parameters to apply when the binding is invoked.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("parameters", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageBindingParameter>? Parameters { get; set; } = default!;

    /// <summary>
    /// Should additional filter context flow when applying the binding.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("acceptsFilterContext", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageBindingAcceptsFilterContext? AcceptsFilterContext { get; set; } = PageBindingAcceptsFilterContext.Default;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:BindingType")]
public enum PageBindingType
{

    [System.Runtime.Serialization.EnumMember(Value = @"Default")]
    /// <summary>No specific usage of this binding.</summary>
    Default,

    [System.Runtime.Serialization.EnumMember(Value = @"Drillthrough")]
    /// <summary>Binding to be used as drillthrough.</summary>
    Drillthrough,

    [System.Runtime.Serialization.EnumMember(Value = @"Tooltip")]
    /// <summary>Binding to be used as tooltip page.</summary>
    Tooltip,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:BindingParameter")]
public partial class PageBindingParameter
{
    /// <summary>
    /// Name of the parameter - unique across the report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Name of the filter which this parameter affects.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("boundFilter", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string BoundFilter { get; set; } = default!;

    /// <summary>
    /// The parameter should be applied when the field of the filter is aggregated.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("asAggregation", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool? AsAggregation { get; set; } = default!;

    /// <summary>
    /// Exactly one instance value should be picked as a filter for this parameter.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("qnaSingleSelectRequired", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool? QnaSingleSelectRequired { get; set; } = default!;

    /// <summary>
    /// Field expression for page binding
    /// </summary>
    [Newtonsoft.Json.JsonProperty("fieldExpr", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public QueryExpressionContainer? FieldExpr { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects")]
public partial class PageFormattingObjects
{
    [Newtonsoft.Json.JsonProperty("pageInformation", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsPageInformation>? PageInformation { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsPageSize>? PageSize { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("background", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsBackground>? Background { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("displayArea", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsDisplayArea>? DisplayArea { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("outspace", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsOutspace>? Outspace { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("outspacePane", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsOutspacePane>? OutspacePane { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("filterCard", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsFilterCard>? FilterCard { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageRefresh", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsPageRefresh>? PageRefresh { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("personalizeVisual", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageFormattingObjectsPersonalizeVisual>? PersonalizeVisual { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageInformation")]
public partial class PageInformation
{
    [Newtonsoft.Json.JsonProperty("pageInformationName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageInformationName { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageInformationQnaPodEnabled", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageInformationQnaPodEnabled { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageInformationAltName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageInformationAltName { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageInformationType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageInformationType { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageSize")]
public partial class PageSize
{
    [Newtonsoft.Json.JsonProperty("pageSizeTypes", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageSizeTypes { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageSizeWidth", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageSizeWidth { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("pageSizeHeight", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PageSizeHeight { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:Background")]
public partial class PageBackground
{
    [Newtonsoft.Json.JsonProperty("color", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Color { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("image", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Image { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("transparency", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Transparency { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:DisplayArea")]
public partial class PageDisplayArea
{
    [Newtonsoft.Json.JsonProperty("verticalAlignment", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? VerticalAlignment { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:OutspacePane")]
public partial class PageOutspacePane
{
    [Newtonsoft.Json.JsonProperty("backgroundColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? BackgroundColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("transparency", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Transparency { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("foregroundColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? ForegroundColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("titleSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? TitleSize { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("searchTextSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? SearchTextSize { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("headerSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? HeaderSize { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("fontFamily", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? FontFamily { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("border", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Border { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("borderColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? BorderColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("checkboxAndApplyColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? CheckboxAndApplyColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("inputBoxColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? InputBoxColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("width", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Width { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:FilterCard")]
public partial class PageFilterCard
{
    [Newtonsoft.Json.JsonProperty("backgroundColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? BackgroundColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("transparency", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Transparency { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("border", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Border { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("borderColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? BorderColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("foregroundColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? ForegroundColor { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("textSize", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? TextSize { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("fontFamily", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? FontFamily { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("inputBoxColor", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? InputBoxColor { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageRefresh")]
public partial class PageRefresh
{
    [Newtonsoft.Json.JsonProperty("show", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Show { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("refreshType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? RefreshType { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("duration", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Duration { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("dialogLauncher", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? DialogLauncher { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("measure", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Measure { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("checkEvery", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? CheckEvery { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PersonalizeVisual")]
public partial class PagePersonalizeVisual
{
    [Newtonsoft.Json.JsonProperty("show", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? Show { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("perspectiveRef", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? PerspectiveRef { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("applyToAllPages", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Newtonsoft.Json.Linq.JToken? ApplyToAllPages { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:VisualInteraction")]
public partial class PageVisualInteraction
{
    /// <summary>
    /// Visual name that will be the source of user interaction (selecting data point for example).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("source", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Source { get; set; } = default!;

    /// <summary>
    /// Visual name for the target of the interaction (selecting data point for example).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("target", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Target { get; set; } = default!;

    /// <summary>
    /// How should the interaction flow from source to target visual (as highlights, as filter, none).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public PageVisualInteractionFilterType Type { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:VisualInteractionFilterType")]
public enum PageVisualInteractionFilterType
{

    [System.Runtime.Serialization.EnumMember(Value = @"Default")]
    /// <summary>The target visual type determines if it should accept the interaction as a highlight or as a filter.</summary>
    Default,

    [System.Runtime.Serialization.EnumMember(Value = @"DataFilter")]
    /// <summary>Data point selection is added as a filter to the target visual.</summary>
    DataFilter,

    [System.Runtime.Serialization.EnumMember(Value = @"HighlightFilter")]
    /// <summary>Data point selection is added as a highlight to the target visual.</summary>
    HighlightFilter,

    [System.Runtime.Serialization.EnumMember(Value = @"NoFilter")]
    /// <summary>Data point selection is ignored by the target visual.</summary>
    NoFilter,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:AutoPageGenerationConfig")]
public partial class PageAutoPageGenerationConfig
{
    /// <summary>
    /// Data fields to use for the auto page generation
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selectedFields", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<QueryExpressionContainer> SelectedFields { get; set; } = new System.Collections.ObjectModel.Collection<QueryExpressionContainer>();

    /// <summary>
    /// Visuals already on the page previously generated by the auto-config
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualContainerConfigurations", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<PageQuickExploreVisualContainerConfig> VisualContainerConfigurations { get; set; } = new System.Collections.ObjectModel.Collection<PageQuickExploreVisualContainerConfig>();

    /// <summary>
    /// The specific layout chosen to render the auto-visuals
    /// </summary>
    [Newtonsoft.Json.JsonProperty("layout", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageQuickExploreLayoutContainer? Layout { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:QuickExploreVisualContainerConfig")]
public partial class PageQuickExploreVisualContainerConfig
{
    /// <summary>
    /// Name of the visual - matches the name property in visual.json files
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Specific data fields used to build this visual from the full set of selected fields
    /// </summary>
    [Newtonsoft.Json.JsonProperty("fields", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public System.Collections.Generic.ICollection<QueryExpressionContainer> Fields { get; set; } = new System.Collections.ObjectModel.Collection<QueryExpressionContainer>();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:QuickExploreLayoutContainer")]
public partial class PageQuickExploreLayoutContainer
{
    /// <summary>
    /// A layout that has 1 hero visual and some related visuals
    /// </summary>
    [Newtonsoft.Json.JsonProperty("related", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageQuickExploreRelatedLayout? Related { get; set; } = default!;

    /// <summary>
    /// Layout that generates visuals purely based on combination of fields
    /// <br/>Deprecated: Use related layout instead.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("combination", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageQuickExploreCombinationLayout? Combination { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:QuickExploreRelatedLayout")]
public partial class PageQuickExploreRelatedLayout
{
    [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Version { get; set; } = 1D;

    /// <summary>
    /// If data table is shown, then the name of that visual
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataTableName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string? DataTableName { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:QuickExploreCombinationLayout")]
public partial class PageQuickExploreCombinationLayout
{
    [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Version { get; set; } = 1D;

    /// <summary>
    /// If data table is shown, then the name of that visual
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataTableName", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string? DataTableName { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:Annotation")]
public partial class PageAnnotation
{
    /// <summary>
    /// Unique name for the annotation.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// A value for this annotation.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Value { get; set; } = default!;


}

/// <summary>
/// Defines a single report page.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json")]
public partial class Page
{
    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json";

    /// <summary>
    /// A unique identifier for the page across the whole report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [System.ComponentModel.DataAnnotations.StringLength(50)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// A user facing name for this page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("displayName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string DisplayName { get; set; } = default!;

    /// <summary>
    /// Defines how the page is scaled.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("displayOption", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public PageDisplayOption DisplayOption { get; set; } = default!;

    /// <summary>
    /// Height of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double? Height { get; set; } = default!;

    /// <summary>
    /// Width of the page (in pixels) - optional only for 'DeprecatedDynamic' option, required otherwise.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("width", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double? Width { get; set; } = default!;

    /// <summary>
    /// Filters that apply to all the visuals on this page - on top of the filters defined for the whole report.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("filterConfig", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public FilterConfiguration? FilterConfig { get; set; } = default!;

    /// <summary>
    /// Additional metadata defined for how this page is used (tooltip, drillthrough, etc).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("pageBinding", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageBinding? PageBinding { get; set; } = default!;

    /// <summary>
    /// Defines the formatting for different objects on a page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("objects", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageFormattingObjects? Objects { get; set; } = default!;

    /// <summary>
    /// Specific usage of this page (for example drillthrough).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("type", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageType? Type { get; set; } = default!;

    /// <summary>
    /// Defines when this page should be visible - by default it is always visible.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visibility", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageVisibility? Visibility { get; set; } = default!;

    /// <summary>
    /// Defines how data point selection on a specific visual flow (as filters) to other visuals on the page.
    /// <br/>By default it is up-to the visual to apply it either as a cross-highlight or as a filter.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualInteractions", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageVisualInteraction>? VisualInteractions { get; set; } = default!;

    /// <summary>
    /// Configuration that was used to automatically generate a page (for example using 'Auto create the report' option).
    /// </summary>
    [Newtonsoft.Json.JsonProperty("autoPageGenerationConfig", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageAutoPageGenerationConfig? AutoPageGenerationConfig { get; set; } = default!;

    /// <summary>
    /// Additional information to be saved (for example comments, readme, etc) for this page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("annotations", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<PageAnnotation>? Annotations { get; set; } = default!;

    /// <summary>
    /// Source of creation of this page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("howCreated", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public PageHowCreated? HowCreated { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageBinding/referenceScope")]
public enum PageBindingReferenceScope
{

    [System.Runtime.Serialization.EnumMember(Value = @"Default")]
    /// <summary>Scope is restricted to the report.</summary>
    Default,

    [System.Runtime.Serialization.EnumMember(Value = @"CrossReport")]
    /// <summary>Scope is across reports - for cross-report drillthrough.</summary>
    CrossReport,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageBinding/acceptsFilterContext")]
public enum PageBindingAcceptsFilterContext
{

    [System.Runtime.Serialization.EnumMember(Value = @"Default")]
    /// <summary>Flows filter context</summary>
    Default,

    [System.Runtime.Serialization.EnumMember(Value = @"None")]
    /// <summary>Additional filter context does not flow to the binding.</summary>
    None,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/pageInformation")]
public partial class PageFormattingObjectsPageInformation
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageInformation Properties { get; set; } = new PageInformation();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/pageSize")]
public partial class PageFormattingObjectsPageSize
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageSize Properties { get; set; } = new PageSize();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/background")]
public partial class PageFormattingObjectsBackground
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageBackground Properties { get; set; } = new PageBackground();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/displayArea")]
public partial class PageFormattingObjectsDisplayArea
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageDisplayArea Properties { get; set; } = new PageDisplayArea();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/outspace")]
public partial class PageFormattingObjectsOutspace
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageBackground Properties { get; set; } = new PageBackground();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/outspacePane")]
public partial class PageFormattingObjectsOutspacePane
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageOutspacePane Properties { get; set; } = new PageOutspacePane();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/filterCard")]
public partial class PageFormattingObjectsFilterCard
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageFilterCard Properties { get; set; } = new PageFilterCard();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/pageRefresh")]
public partial class PageFormattingObjectsPageRefresh
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PageRefresh Properties { get; set; } = new PageRefresh();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "definitions:PageFormattingObjects/personalizeVisual")]
public partial class PageFormattingObjectsPersonalizeVisual
{
    /// <summary>
    /// Defines the scope at which to apply the formatting for this object.
    /// <br/>Can also define rules for matching highlighted values and how multiple definitions for the same property should be ordered.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("selector", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public Selector? Selector { get; set; } = default!;

    /// <summary>
    /// Describes the properties of the object to apply formatting changes to.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("properties", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public PagePersonalizeVisual Properties { get; set; } = new PagePersonalizeVisual();


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "type")]
public enum PageType
{

    [System.Runtime.Serialization.EnumMember(Value = @"Drillthrough")]
    /// <summary>Page to be used as drillthrough.</summary>
    Drillthrough,

    [System.Runtime.Serialization.EnumMember(Value = @"Tooltip")]
    /// <summary>Page to be used as tooltip.</summary>
    Tooltip,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "visibility")]
public enum PageVisibility
{

    [System.Runtime.Serialization.EnumMember(Value = @"AlwaysVisible")]
    /// <summary>Page is always shown in the pages list</summary>
    AlwaysVisible,

    [System.Runtime.Serialization.EnumMember(Value = @"HiddenInViewMode")]
    /// <summary>Page is not visible when viewing report in View mode.</summary>
    HiddenInViewMode,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/page/1.3.0/schema.json", "howCreated")]
public enum PageHowCreated
{

    [System.Runtime.Serialization.EnumMember(Value = @"Default")]
    /// <summary>Page is generated by user interaction.</summary>
    Default,

    [System.Runtime.Serialization.EnumMember(Value = @"Copilot")]
    /// <summary>Page is created by copilot.</summary>
    Copilot,

}