//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:ReportExtensionEntity")]
public partial class ReportExtensionEntity
{
    /// <summary>
    /// Name of the extension entity - must match a name in the semantic model.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Additional measures to include on this entity.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("measures", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<ReportExtensionMeasure> Measures { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:ReportExtensionMeasure")]
public partial class ReportExtensionMeasure
{
    /// <summary>
    /// Name of the extension measure - must be unique across the semantic model and other extension measures.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Data type for the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataType", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public ReportExtensionPrimitiveTypeName DataType { get; set; } = default!;

    /// <summary>
    /// Extended data category for the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("dataCategory", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string DataCategory { get; set; } = default!;

    /// <summary>
    /// DAX expression for this measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("expression", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Expression { get; set; } = default!;

    /// <summary>
    /// Sets the measure to be hidden.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("hidden", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool Hidden { get; set; } = default!;

    /// <summary>
    /// Format string for this measure in VBA format.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("formatString", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string FormatString { get; set; } = default!;

    /// <summary>
    /// Template information that was used to create this measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("measureTemplate", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public ReportExtensionMeasureTemplate MeasureTemplate { get; set; } = default!;

    /// <summary>
    /// A description for the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("description", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Description { get; set; } = default!;

    /// <summary>
    /// Display folder for the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("displayFolder", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string DisplayFolder { get; set; } = default!;

    /// <summary>
    /// Additional annotations to include for this measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("annotations", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<ReportExtensionMeasureExtensionAnnotation> Annotations { get; set; } = default!;

    /// <summary>
    /// References to other model measures and extensions used in the DAX of this measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("references", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public ReportExtensionExpressionReferences References { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:PrimitiveTypeName")]
public enum ReportExtensionPrimitiveTypeName
{

    [System.Runtime.Serialization.EnumMember(Value = @"Binary")]
    Binary = 0,

    [System.Runtime.Serialization.EnumMember(Value = @"Boolean")]
    Boolean = 1,

    [System.Runtime.Serialization.EnumMember(Value = @"Date")]
    Date = 2,

    [System.Runtime.Serialization.EnumMember(Value = @"DateTime")]
    DateTime = 3,

    [System.Runtime.Serialization.EnumMember(Value = @"DateTimeZone")]
    DateTimeZone = 4,

    [System.Runtime.Serialization.EnumMember(Value = @"Decimal")]
    Decimal = 5,

    [System.Runtime.Serialization.EnumMember(Value = @"Double")]
    Double = 6,

    [System.Runtime.Serialization.EnumMember(Value = @"Duration")]
    Duration = 7,

    [System.Runtime.Serialization.EnumMember(Value = @"Integer")]
    Integer = 8,

    [System.Runtime.Serialization.EnumMember(Value = @"Json")]
    Json = 9,

    [System.Runtime.Serialization.EnumMember(Value = @"None")]
    None = 10,

    [System.Runtime.Serialization.EnumMember(Value = @"Null")]
    Null = 11,

    [System.Runtime.Serialization.EnumMember(Value = @"Text")]
    Text = 12,

    [System.Runtime.Serialization.EnumMember(Value = @"Time")]
    Time = 13,

    [System.Runtime.Serialization.EnumMember(Value = @"Variant")]
    Variant = 14,

}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:ReportExtensionMeasureTemplate")]
public partial class ReportExtensionMeasureTemplate
{
    /// <summary>
    /// Name of the template.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("daxTemplateName", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string DaxTemplateName { get; set; } = default!;

    /// <summary>
    /// Version of the template used.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Version { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:MeasureExtensionAnnotation")]
public partial class ReportExtensionMeasureExtensionAnnotation
{
    /// <summary>
    /// Unique name for this annotation.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// Value for the annotation.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("value", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Value { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:ExpressionReferences")]
public partial class ReportExtensionExpressionReferences
{
    /// <summary>
    /// False if all references are recognized.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("unrecognizedReferences", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public bool UnrecognizedReferences { get; set; } = default!;

    /// <summary>
    /// References to model measures and other extensions.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("measures", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<ReportExtensionMeasureReference> Measures { get; set; } = default!;


}

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json", "definitions:MeasureReference")]
public partial class ReportExtensionMeasureReference
{
    /// <summary>
    /// Name of the schema - leave empty if using model measures. Use name of extension if using other measures from the extension.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public string Schema { get; set; } = default!;

    /// <summary>
    /// Entity name of the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("entity", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Entity { get; set; } = default!;

    /// <summary>
    /// Name of the measure.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = default!;


}

/// <summary>
/// Defines a report extension and its references.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.0.0-54+Branch.main.Sha.a1360a683aa4474dcf4ea6e3152e0be355b399d4.a1360a683aa4474dcf4ea6e3152e0be355b399d4, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json")]
public partial class ReportExtension
{
    /// <summary>
    /// Name of the extension.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Name { get; set; } = "extension";

    /// <summary>
    /// Entities in the semantic model that are extended.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("entities", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.ICollection<ReportExtensionEntity> Entities { get; set; } = default!;

    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/reportExtension/1.0.0/schema.json";


}