//----------------------
// <auto-generated>
//     Generated using FabricTools.Items.CodeGeneration 1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0) (http://github.com/FabricTools)
// </auto-generated>
//----------------------


#nullable enable


namespace FabricTools.Items.Report.Definitions;

#pragma warning disable // Disable all warnings

[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainerMobileState/1.4.0/schema.json", "definitions:VisualContainerPosition")]
public partial class VisualContainerMobileStateVisualContainerPosition
{
    /// <summary>
    /// Horizontal position of the left edge of the visual.
    /// <br/>Should be between 0 and width of the containing page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("x", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double X { get; set; } = default!;

    /// <summary>
    /// Vertical position of the top edge of the visual.
    /// <br/>Should be between 0 and height of the containing page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("y", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Y { get; set; } = default!;

    /// <summary>
    /// Defines the stacking order for the visual.
    /// <br/>Higher z-index visuals are shown on top of the lower ones.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("z", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double? Z { get; set; } = default!;

    /// <summary>
    /// Height of the visual.
    /// <br/>y + height should be less than the height of the containing page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("height", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Height { get; set; } = default!;

    /// <summary>
    /// Width of the visual.
    /// <br/>x + width should be less than the width of the containing page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("width", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double Width { get; set; } = default!;

    /// <summary>
    /// Defines the selection order for this visual when using keyboard (tab key)
    /// <br/>to navigate the visuals on the containing page.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("tabOrder", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double? TabOrder { get; set; } = default!;

    [Newtonsoft.Json.JsonProperty("angle", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public double? Angle { get; set; } = default!;


}

/// <summary>
/// Defines information about a visual container's mobile layout.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("FabricTools.Items.CodeGeneration", "1.1.0+Branch.main.Sha.20b425801c5e5ce25afea6ff55befe43818af959.20b425801c5e5ce25afea6ff55befe43818af959, NJsonSchema: 11.2.0.0 (Newtonsoft.Json v13.0.0.0)")]
[FabricTools.Items.ComponentModel.SourceSchema("https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainerMobileState/1.4.0/schema.json")]
public partial class VisualContainerMobileState
{
    /// <summary>
    /// Defines the schema to use for an item.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("$schema", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
    public string Schema { get; set; } = "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainerMobileState/1.4.0/schema.json";

    /// <summary>
    /// Specifies the mobile specific formatting changes for different "objects" of a visual.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("objects", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public System.Collections.Generic.IDictionary<string, System.Collections.Generic.ICollection<DataViewObjectDefinition>>? Objects { get; set; } = default!;

    /// <summary>
    /// Specifies the mobile specific formatting changes for different "objects" of the visual container.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("visualContainerObjects", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    public VisualConfigurationVisualContainerFormattingObjects? VisualContainerObjects { get; set; } = default!;

    /// <summary>
    /// Describes a mobile specific position for this visuals.
    /// </summary>
    [Newtonsoft.Json.JsonProperty("position", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
    [System.ComponentModel.DataAnnotations.Required]
    public VisualContainerMobileStateVisualContainerPosition Position { get; set; } = new VisualContainerMobileStateVisualContainerPosition();


}