// <auto-generated/>

namespace FabricTools.Items.Report.Definitions;

#nullable enable

public partial class VisualContainer
{
    #region IPbirDocument
                        
    string IPbirDocument.GetDefaultSchema() => "https://developer.microsoft.com/json-schemas/fabric/item/report/definition/visualContainer/1.7.0/schema.json";
                                            
    #endregion
}